const ActionType = {
  SET_CURRENT_CONTENT: 'SET_CURRENT_CONTENT',
  SET_CURRENT_FOLDER: 'SET_CURRENT_FOLDER',
  DELETE_CONTENT: 'DELETE_CONTENT',
  DELETE_FOLDER: 'DELETE_FOLDER',

  SET_ACTIVE_SERVICE: `SET_ACTIVE_SERVICE`,
  SET_WEEKS_AMOUNT: 'SET_WEEKS_AMOUNT',
  CLEAR_TASKS: 'CLEAR_TASKS',
  CHANGE_TASK: 'CHANGE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  SET_MERGE_TASKS: 'SET_MERGE_TASKS',
  REPLACE_TASKS: 'REPLACE_TASKS',
  SET_DELTA: 'SET_DELTA',
  SET_VIEWED_USER: 'SET_VIEWED_USER',
  SET_LOADED_USER: 'SET_LOADED_USER',
  DELETE_LOADED_USER: 'DELETE_LOADED_USER',
  CLEAR_VIEW_LOAD: 'CLEAR_VIEW_LOAD',
}

export default ActionType
