const ActionType = {
  SET_CURRENT_CONTENT: 'SET_CURRENT_CONTENT',
  CREATE_CONTENT: 'CREATE_CONTENT',
  SAVE_CONTENT: 'SAVE_CONTENT',
  DELETE_CONTENT: 'DELETE_CONTENT',
  DELETE_MULTIPLE: 'DELETE_MULTIPLE',
  // SEND_HTML: 'SEND_HTML',
  // SEND_SMS: 'SEND_SMS',

  SET_CURRENT_FOLDER: 'SET_CURRENT_FOLDER',
  CREATE_FOLDER: 'CREATE_FOLDER',
  RENAME_FOLDER: 'RENAME_FOLDER',
  DELETE_FOLDER: 'DELETE_FOLDER',
}

export default ActionType
