const ActionType = {
  SET_CURRENT_CONTENT: 'SET_CURRENT_CONTENT',
  CREATE_CONTENT: 'CREATE_CONTENT',
  SAVE_CONTENT: 'SAVE_CONTENT',
  DELETE_CONTENT: 'DELETE_CONTENT',
  DELETE_MULTIPLE: 'DELETE_MULTIPLE',
  // SEND_HTML: 'SEND_HTML',
  // SEND_SMS: 'SEND_SMS',
}

export default ActionType
