export const data = [
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасоновфывфывыфвфв',
    firstName: 'Дмитрийфывфывфывфывфыв',
    patronym: 'Сергеевичфвфывфывфвфывфыв',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
  {
    id: 2145,
    lastName: 'Катасонов',
    firstName: 'Дмитрий',
    patronym: 'Сергеевич',
    email: 'sergeev@yandex.ru',
    phone: '89169994455',
    city: 'Москва',
    speciality: 'Терапевт',
    segment: 'Активный',
  },
]
