const ActionType = {
  ADD_MANY_DOCTORS: 'ADD_MANY_DOCTORS',
  ADD_DOCTOR: 'ADD_DOCTOR',
  CLEAR_DOCTORS: 'CLEAR_DOCTORS',
  DELETE_DOCTOR: 'DELETE_DOCTOR',
  DELETE_MULTIPLE_DOCTORS: 'DELETE_MULTIPLE_DOCTORS',
  COPY_MULTIPLE_DOCTORS: 'COPY_MULTIPLE_DOCTORS',
  EDIT_DOCTOR_FIELD: 'EDIT_DOCTOR_FIELD',
}

export default ActionType
