const ActionType = {
  INIT_ALL_AUDIENCES: 'INIT_ALL_AUDIENCES',
  SET_CURRENT_AUDIENCE: 'SET_CURRENT_AUDIENCE',
  UPDATE_AUDIENCE_INFO: 'UPDATE_AUDIENCE_INFO',
  CLEAR_AUDIENCES: 'CLEAR_AUDIENCES',
}

export default ActionType
