const ActionType = {
  VIEW_FOLDER: 'VIEW_FOLDER',
  CREATE_FOLDER: 'CREATE_FOLDER',
  RENAME_FOLDER: 'RENAME_FOLDER',
  DELETE_FOLDER: 'DELETE_FOLDER',
  INCREMENT_FOLDER: 'INCREMENT_FOLDER',
  DECREMENT_FOLDER: 'DECREMENT_FOLDER',
}

export default ActionType
