const ActionType = {
  SET_CURRENT_FOLDER: 'SET_CURRENT_FOLDER',
  VIEW_FOLDER: 'VIEW_FOLDER',
  CREATE_FOLDER: 'CREATE_FOLDER',
  RENAME_FOLDER: 'RENAME_FOLDER',
  DELETE_FOLDER: 'DELETE_FOLDER',
}

export default ActionType
